### ISSUE TITLE
No longer works with python3

### ISSUE THREAD

**Issue by julianhughes** [alphapapa/mpdsync#3]
`  File "/home/julian/bin/mpdsync.py", line 20
    print 'ERROR: This script requires python-mpd2 >= 0.5.4.'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?`

I checked I have python-mpd2: `pip install --user python-mpd2
Requirement already satisfied: python-mpd2 in /usr/lib/python3/dist-packages (3.0.5)`

and `apt search python-mpd |grep installed
...
python3-mpd/testing,testing,unstable,unstable,now 3.0.5-1 all [installed]
python3-musicpd/testing,testing,unstable,unstable,now 0.8.0-1 all [installed]`

Also if I comment out the version check and try again I get this: `:~$ mpdsync.py 
Traceback (most recent call last):
  File "/home/julian/bin/mpdsync.py", line 1395, in <module>
    sys.exit(main())
  File "/home/julian/bin/mpdsync.py", line 1297, in main
    if args.verbose >= 3:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
`

**Comment by alphapapa** [comment]
Hi Julian,

Thanks for reporting this.  I didn't know that anyone was actually using this script anymore.  I haven't used it myself for a while, and I haven't tried running it on Python 3.  Probably it just needs to be tidied up for compatibility with Python 3.  Patches welcome, or maybe I'll get around to it eventually.  :)

**Comment by julianhughes** [comment]
Thanks for responding, much appreciated.  If it was a bash script I'd have a go at fixing it but unfortunately I know zip about python.  I think mpd is interesting again as pipewire is such a big improvement over pulseaudio, and there is finally a full featured and seriously good Android client https://mafa.indi.software which allows streaming and doesn't choke when bit depth or sample rate change.  mpd looks much more interesting for multi-room and mobile use now than it did a few years ago.

**Comment by samuelbruce** [comment]
I wanted to try this script out, so I've spent a little time making it compatible with Python 3. I've done only basic testing but have run it successfully under Python versions 3.12.1 and 2.7.12. I'll endeavour to submit a pull request soon.

**Comment by samuelbruce** [comment]
Since PR #4 has been merged, could this issue be considered closed? :)

**Comment by alphapapa** [comment]
Yes, thanks.
